Repository FRONTENDBOOTCAMP-13th/Final-10-console.10g, pull requests merged in 2025-07, with the labels that each got.

#4 🎨 Feat: 기능 추가, 변경
  src/app/globals.css
Labels: feature

#11 🐛 Fix: 경로 수정
  src/app/layout.tsx
Labels: bug

#14 🎨 feat: 푸터 구현
  public/logo.png
  src/app/page.tsx
  src/components/common/Footer.tsx
  src/components/icon/GithubIcon.tsx
  src/components/icon/KakaoIcon.tsx
  src/components/icon/NotionIcon.tsx
Labels: feature

#18 💄 style: 푸터 디자인 수정
  public/logo.png
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
Labels: design

#23 🎨 Feat: 기능 추가, 변경
  api/bruno/team/final/final/상품 목록 조회.bru
  api/dbinit/team/data.js
  public/files/febc13-final10-emjf/sample-diver.jpg
  public/files/febc13-final10-emjf/sample-dog.jpg
  src/app/apitest/page.tsx
  src/types/Product.ts
  src/types/api.ts
  src/utils/getProducts.ts
Labels: api

#22 🎨 feat: 헤더 반응형 구현 및 검색 바 구현
  src/components/common/DesktopHeader.tsx
  src/components/common/Header.tsx
  src/components/common/MobileHeader.tsx
  src/components/icon/ArrowIcon.tsx
  src/components/icon/BellIcon.tsx
  src/components/icon/CartIcon.tsx
  src/components/icon/CloseIcon.tsx
  src/components/icon/MypageIcon.tsx
  src/components/icon/SearchIcon.tsx
  src/constants/categories.ts
Labels: feature, design

#25 🐛 fix: 헤더 모바일 버전 버그 해결
  src/components/common/MobileHeader.tsx
Labels: bug

#28 🧪test : 테스트 코드 추가, 삭제, 변경 등
  api/dbinit/team/data.js
  next.config.ts
  public/files/febc13-final10-emjf/sample-diver.jpg
  public/files/febc13-final10-emjf/sample-dog.jpg
  src/app/apitest/page.tsx
Labels: test, api

#36 🎨 feat: 문의, 공지, 커뮤니티 게시판 목록 조회 fetching
  api/bruno/team/final/final/공지게시판 목록 조회.bru
  api/bruno/team/final/final/문의게시판 목록 조회.bru
  api/bruno/team/final/final/문의게시판 상세 조회.bru
  api/bruno/team/final/final/자유게시판 목록 조회.bru
  api/bruno/team/final/final/회원 상세 조회.bru
  api/dbinit/team/data.js
  src/app/apitest/page.tsx
  src/types/Post.ts
  src/utils/getPosts.ts
Labels: api, data

#40 🎨feat: 회원가입 페이지
  next.config.ts
  package-lock.json
  package.json
  src/app/(user)/signup/AgreementSection.tsx
  src/app/(user)/signup/BirthdayField.tsx
  src/app/(user)/signup/EmailField.tsx
  src/app/(user)/signup/NameField.tsx
  src/app/(user)/signup/PasswordConfirmField.tsx
  src/app/(user)/signup/PasswordField.tsx
  src/app/(user)/signup/PhoneField.tsx
  src/app/(user)/signup/ProfileImageField.tsx
  src/app/(user)/signup/SignupForm.tsx
  src/app/(user)/signup/page.tsx
  src/data/actions/file.ts
  src/data/actions/user.ts
  src/types/User.ts
  src/types/file.ts
  src/types/index.ts
Labels: feature

#41 🎨feat: 예외 상황 대응 페이지
  public/404-dotori.png
  public/error-dotori.png
  public/loading-dotori.png
  src/app/error.tsx
  src/app/fallback-test/test-error/error.tsx
  src/app/fallback-test/test-error/page.tsx
  src/app/fallback-test/test-loading/loading.tsx
  src/app/fallback-test/test-loading/page.tsx
  src/app/loading.tsx
  src/app/not-found.tsx
Labels: feature

#62 🎨 feat: 마이페이지 관심상품 제작
  src/app/mypage/wishlist/ProductCard.tsx
  src/app/mypage/wishlist/page.tsx
  src/components/icon/FavoriteBorderIcon.tsx
  src/components/icon/FavoriteIcon.tsx
  src/data/actions/addBookmark.ts
  src/data/actions/deleteBookmark.ts
  src/stores/loginStore.ts
  src/utils/getProducts.ts
Labels: feature

#68 🎨 feat: 마이페이지 배송지 등록 제작
  src/app/mypage/address/add/page.tsx
  src/app/mypage/address/edit/[id]/page.tsx
  src/app/mypage/address/page.tsx
  src/app/mypage/myposts/page.tsx
  src/app/mypage/recently-viewed/page.tsx
  src/app/mypage/wishlist/page.tsx
  src/data/actions/addAddress.ts
  src/types/User.ts
Labels: feature

#81 🎨 feat: 카테고리 별 상품 목록 페이지 구현
  public/sad-dotori.png
  src/app/category/CategoryPage.tsx
  src/app/category/all/page.tsx
  src/app/category/character/page.tsx
  src/app/category/figure/page.tsx
  src/app/category/living-accessories/page.tsx
  src/app/category/miniature/page.tsx
  src/app/category/new/page.tsx
  src/app/category/popular/page.tsx
  src/app/category/randombox/page.tsx
  src/app/category/stationery/page.tsx
  src/components/common/DesktopHeader.tsx
  src/components/common/MobileHeader.tsx
  src/components/common/ProductCard.tsx
  src/components/common/ProductGrid.tsx
  src/components/common/ProductItemCard.tsx
  src/constants/categories.ts
  src/styles/globals.css
  src/utils/getProducts.ts
Labels: feature, design

#82 🐛 fix: url 쿼리 문자열 오타 수정
  src/utils/getProducts.ts
Labels: bug

#86 🎨 feat: 메인페이지
  public/atashinchi-thumb.png
  public/character/chiikawa.png
  public/character/disney-pixar.png
  public/character/ghibli.png
  public/character/miffy.png
  public/character/pingu.png
  public/character/sanrio.png
  public/character/shinchang.png
  public/character/snoopy.png
  public/chiikawa-thumb.png
  public/conan-thumb.png
  public/main-banner1.png
  public/main-banner2.png
  public/main-banner3.png
  public/main-dotori.png
  src/app/loading.tsx
  src/app/page.tsx
  src/app/story/[slug]/page.tsx
  src/components/common/ProductCard.tsx
  src/components/common/ProductCardSkeleton.tsx
  src/components/common/ProductGrid.tsx
  src/components/main/Carousel.tsx
  src/components/main/CategorySlider.tsx
  src/components/main/NewProductsSection.tsx
  src/components/main/ReviewSlider.tsx
  src/components/main/SectionTitle.tsx
  src/components/main/StoryCard.tsx
  src/components/main/StoryCardList.tsx
  src/data/stories/chiikawa.ts
  src/styles/globals.css
Labels: feature

#88 🎨 feat: 내가 쓴 글 페이지 제작
  src/app/mypage/myposts/page.tsx
  src/styles/globals.css
  src/utils/getPosts.ts
Labels: feature

#95 🚀 deploy: 배포 테스트
  api/bruno/team/final/final/게시글 삭제.bru
  api/bruno/team/final/final/로그인.bru
  src/actions/post.ts
  src/app/board/community/new/ImagePostForm.tsx
  src/app/board/community/page.tsx
  src/app/board/qna/new/NewQnaForm.tsx
  src/app/board/qna/new/ProductSearchModal.tsx
  src/app/mypage/logout/page.tsx
  src/types/Post.ts
Labels: deploy

#104 🎨 feat: 정렬 기능 추가
  src/app/category/CategoryPage.tsx
Labels: feature

#107 🎨 feat: 검색 페이지 구현
  public/chiikawa-heart.png
  public/chiikawa-stand.png
  public/chiikawa-three.webp
  public/chiikawa.webp
  public/kitty-color.png
  public/kitty.png
  src/app/category/CategoryPage.tsx
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/components/common/DesktopHeader.tsx
  src/components/common/MobileHeader.tsx
  src/utils/getProducts.ts
Labels: bug, feature, design

#110 🎨 feat: 주민증 제작
  public/mypage-profile.png
  src/app/mypage/ResidentCard.tsx
  src/app/mypage/address/add/page.tsx
  src/app/mypage/address/edit/[id]/page.tsx
  src/app/mypage/myposts/page.tsx
  src/app/mypage/page.tsx
  src/data/actions/addAddress.ts
  src/data/actions/patcUserIntro.ts
  src/data/actions/patchUserAddresses.ts
  src/data/actions/patchUserImage.ts
  src/types/User.ts
  src/types/UserAddressRes.ts
  src/utils/getUsers.ts
Labels: feature

#116 🎨 상품 상세 페이지 진행중
  public/back-dotori.png
  src/app/products/[id]/DetailPage.tsx
  src/app/products/[id]/Info.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/products/[id]/Questions.tsx
  src/app/products/[id]/Reviews.tsx
  src/app/products/[id]/ShoppingGuide.tsx
  src/app/products/[id]/TabSection.tsx
  src/app/products/[id]/page.tsx
  src/app/story/[slug]/story-content.tsx
  src/components/common/Breadcrumb.tsx
  src/components/common/DotBackgroundWrapper.tsx
  src/components/common/ProductCard.tsx
  src/components/common/ProductItemCard.tsx
  src/components/icon/ShareIcon.tsx
  src/components/main/NewProductsSection.tsx
  src/constants/categories.ts
  src/hooks/useQuantityHandlers.ts
  src/hooks/useRemainingStock.ts
  src/hooks/useToggleBookmark.ts
  src/styles/globals.css
  src/utils/getProducts.ts
Labels: feature

#117 🎨 feat: 자유게시판 이미지 클릭시 모달 기능 추가
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/community/ImageModal.tsx
  src/data/actions/addBookmark.ts
Labels: enhancement

#121 ♻️ refactor: 코드 리팩토링
  src/app/board/notice/[id]/DesktopNoticeDetail.tsx
  src/app/board/notice/[id]/MobileNoticeDetail.tsx
  src/app/board/notice/[id]/page.tsx
  src/app/board/qna/[id]/DesktopQNADetail.tsx
  src/app/board/qna/[id]/MobileQNADetail.tsx
  src/app/board/qna/[id]/page.tsx
  src/app/board/qna/page.tsx
  src/app/category/CategoryPage.tsx
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/components/common/DesktopHeader.tsx
  src/components/common/MobileHeader.tsx
  src/components/common/NotificationIcon.tsx
  src/types/Product.ts
Labels: refactor

#123 🎨 문의 게시판 이미지 추가
  src/app/board/qna/page.tsx
  src/types/Post.ts
Labels: enhancement

#130 🎨 feat: 인기 상품에 링크 걸기, 카드에 호버 애니메이션 효과 넣기
  src/components/common/ProductCard.tsx
  src/components/main/CategorySlider.tsx
Labels: enhancement, design

#133 🎨feat: 상품 상세 페이지(리뷰 탭 제외)
  public/page-dotori.png
  src/app/board/qna/new/NewQnaForm.tsx
  src/app/products/[id]/DetailPage.tsx
  src/app/products/[id]/Info.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/products/[id]/Questions.tsx
  src/app/products/[id]/TabSection.tsx
  src/app/products/[id]/page.tsx
  src/components/common/Pagination.tsx
Labels: feature

#134 💄 style: 페이지 번호 버튼 스타일 변경
  src/components/common/Pagination.tsx
Labels: design

#137 🎨 feat: 장바구니 페이지 제작
  src/app/cart/page.tsx
  src/app/order/OrderUserInfo.tsx
  src/app/order/page.tsx
  src/data/actions/deleteCartItem.ts
  src/data/actions/deleteCartItems.ts
  src/data/actions/patchCartQuantity.ts
  src/stores/cartQuantityStore.ts
  src/types/Cart.ts
  src/types/Order.ts
  src/utils/getCarts.ts
Labels: feature

#139 🎨 feat: 자유게시판 글 작성 페이지 기능 추가
  api/bruno/team/final/final/파일 업로드 조회.bru
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/community/new/ImagePostForm.tsx
  src/app/board/community/new/page.tsx
  src/app/board/qna/new/NewQnaForm.tsx
  src/app/board/qna/new/page.tsx
Labels: enhancement

#141 🎨 feat: 헤더 컴포넌트 hover 로직 추가
  src/components/common/DesktopHeader.tsx
Labels: enhancement

#145 🎨 feat: order 페이지 제작
  public/order-kakaopay.png
  public/order-naverpay.png
  public/order-tosspay.png
  src/app/cart/page.tsx
  src/app/order/OrderClient.tsx
  src/app/order/OrderCostSummary.tsx
  src/app/order/OrderPayment.tsx
  src/app/order/OrderProductList.tsx
  src/app/order/OrderUserInfo.tsx
  src/app/order/OrderWrapper.tsx
  src/app/order/page.tsx
  src/data/actions/createOrder.ts
  src/types/Cart.ts
  src/types/Order.ts
Labels: feature

#148 🎨 feat: 자유게시판 댓글 기능 구현
  api/bruno/team/final/final/게시글 댓글 조회.bru
  api/bruno/team/final/final/게시글 댓글 추가.bru
  src/app/apitest/page.tsx
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/community/ImageModal.tsx
  src/components/icon/CommentIcon.tsx
  src/data/actions/post.ts
Labels: enhancement, api

#150 🎨 feat: 결제완료 페이지 제작
  public/order-shoppingbag.png
  src/app/order/OrderWrapper.tsx
  src/app/order/complete/[id]/OrderCompleteHeader.tsx
  src/app/order/complete/[id]/OrderCompleteProducts.tsx
  src/app/order/complete/[id]/OrderCompleteUserInfo.tsx
  src/app/order/complete/[id]/OrderCompleteWrapper.tsx
  src/app/order/complete/[id]/page.tsx
  src/types/Order.ts
  src/utils/getOrders.ts
Labels: feature

#153 🎨 feat: 페이지네이션 및 검색탭 기능 추가
  src/app/board/community/CommunityBoardClientWrapper.tsx
  src/app/board/community/page.tsx
  src/data/actions/post.ts
Labels: enhancement

#156 🎨 feat: 알림 수신 방식을 polling에서 상태 기반으로 개선
  src/app/paytest/page.tsx
  src/components/common/NotificationIcon.tsx
  src/stores/notificationStore.ts
  src/stores/userStore.ts
Labels: bug, enhancement

#168 🎨 상품 상세 문의/리뷰 기능
  src/app/page.tsx
  src/app/products/[id]/DetailPage.tsx
  src/app/products/[id]/ProductDetailPage.tsx
  src/app/products/[id]/ProductInfo.tsx
  src/app/products/[id]/ProductQuestions.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/products/[id]/Questions.tsx
  src/app/products/[id]/Reviews.tsx
  src/app/products/[id]/TabSection.tsx
  src/app/products/[id]/page.tsx
  src/app/products/[id]/review/ReviewFilterTabs.tsx
  src/app/products/[id]/review/ReviewImageModal.tsx
  src/app/products/[id]/review/ReviewImages.tsx
  src/app/products/[id]/review/ReviewItem.tsx
  src/app/products/[id]/review/ReviewList.tsx
  src/app/products/[id]/review/ReviewSortDropdown.tsx
  src/app/products/[id]/review/ReviewWriteButton.tsx
  src/app/products/[id]/review/index.tsx
  src/components/common/ReviewModal.tsx
  src/data/actions/addReview.ts
  src/data/actions/deleteReview.ts
  src/data/actions/file.ts
  src/data/actions/patchReview.ts
  src/types/Review.ts
  src/utils/getReviews.ts
  src/utils/mask.ts
Labels: bug, feature

#169 🐛 fix: 북마크 기능, 회원 정보 수정 기능 등 버그 개선 및 UI 기능 개선
  public/font/pretendardvariable.css
  public/font/woff2/PretendardVariable.woff2
  public/kitty-color.png
  src/app/category/CategoryPage.tsx
  src/app/mypage/MypageInfo.tsx
  src/app/mypage/OrderHistory.tsx
  src/app/mypage/ResidentCard.tsx
  src/app/mypage/edit-info/EditForm.tsx
  src/app/mypage/myposts/page.tsx
  src/app/mypage/wishlist/page.tsx
  src/components/common/DesktopHeader.tsx
  src/components/common/Footer.tsx
  src/components/common/NotificationIcon.tsx
  src/components/main/NewProductsSection.tsx
  src/data/actions/addBookmark.ts
  src/styles/globals.css
Labels: bug, enhancement, design

#167 🎨 feat: 문의 상세 페이지 리팩토링 및 문의 수정 서버 액션 추가
  api/bruno/team/final/final/게시물 수정.bru
  src/app/board/qna/QnaBoardClientWrapper.tsx
  src/app/board/qna/[id]/DesktopQNADetail.tsx
  src/app/board/qna/[id]/MobileQNADetail.tsx
  src/app/board/qna/[id]/QNADetailClient.tsx
  src/app/board/qna/[id]/page.tsx
  src/app/board/qna/edit/[id]/EditQnaForm.tsx
  src/app/board/qna/edit/[id]/page.tsx
  src/data/actions/post.ts
  src/types/Post.ts
Labels: enhancement

#171 🎨 feat: 결제 완료 시 알림 연결
  src/app/cart/page.tsx
  src/app/order/OrderWrapper.tsx
  src/styles/globals.css
Labels: feature

#174 💄style: 상품 상세 스타일 조정
  src/app/products/[id]/PurchaseSection.tsx
  src/app/products/[id]/review/ReviewItem.tsx
  src/app/products/[id]/review/index.tsx
Labels: design

#181 💄style: 파비콘 설정
  public/favicon.png
  src/app/favicon.ico
  src/app/layout.tsx
Labels: design

#183 Feat/main 61
  src/app/products/[id]/TabSection.tsx
  src/components/common/DotBackgroundWrapper.tsx
  src/components/main/BestReviewCard.tsx
  src/components/main/CategorySlider.tsx
  src/styles/globals.css
Labels: design

#189 🚀 deploy: 배포 테스트
  src/app/apitest/page.tsx
  src/app/board/community/page.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/page.tsx
Labels: deploy

#193 💄 style: 관리자 계정 마이페이지 UI 제작
  src/app/mypage/MypageInfo.tsx
Labels: design

#196 🎨 feat: 연관상품 기능 추가
  src/app/products/[id]/ProductDetailPage.tsx
  src/app/products/[id]/RelatedProducts.tsx
  src/components/common/ProductCard.tsx
Labels: feature

#195 💄style: 반응형 디자인 수정
  src/app/board/community/CommunityBoardClientWrapper.tsx
  src/app/board/community/ImageModal.tsx
  src/app/board/notice/NoticeBoardClientWrapper.tsx
  src/app/board/qna/QnaBoardClientWrapper.tsx
  src/app/board/qna/new/NewQnaForm.tsx
Labels: design

#204 🎨 feat: 관리자 통계 조회를 위한 페이지 생성
  api/bruno/team/final/final/통계 조회(상품별).bru
  api/bruno/team/final/final/통계 조회(일별).bru
  src/app/mypage/stats/StatsClient.tsx
  src/app/mypage/stats/page.tsx
  src/types/stats.ts
  src/utils/getStats.ts
Labels: enhancement

#207 📄 page : 페이지 경로 변경
  api/bruno/team/final/final/통계 조회(상품별).bru
  api/bruno/team/final/final/통계 조회(일별).bru
  src/app/mypage/MypageInfo.tsx
  src/app/mypage/admin/stats/StatsClient.tsx
  src/app/mypage/admin/stats/page.tsx
Labels: feature

#209 🎨 feat: 데스크탑 헤더 자동완성 기능 추가
  src/components/common/DesktopHeader.tsx
Labels: enhancement

#211 💄 style: 게시판 UI 일부 변경
  api/bruno/team/02_일반 회원/06_알림메세지/folder.bru
  api/bruno/team/02_일반 회원/06_알림메세지/내 알림 목록 조회.bru
  api/bruno/team/02_일반 회원/06_알림메세지/알림 메세지 읽음.bru
  api/bruno/team/02_일반 회원/06_알림메세지/알림 메시지 보내기.bru
  api/bruno/team/02_일반 회원/06_알림메세지/알림 메시지 삭제.bru
  api/bruno/team/02_일반 회원/folder.bru
  api/bruno/team/05_게시판(QnA, 공지 등)/folder.bru
  api/bruno/team/06_시스템/folder.bru
  api/bruno/team/console.10g/folder.bru
  api/bruno/team/final/folder.bru
  api/dbinit/team/data.js
  src/app/board/community/CommunityBoardClientWrapper.tsx
  src/app/board/community/CommunityWriteButton.tsx
  src/app/board/community/page.tsx
  src/app/board/notice/NoticeBoardClientWrapper.tsx
  src/app/board/notice/page.tsx
  src/app/board/qna/QnaBoardClientWrapper.tsx
  src/app/board/qna/QnaWriteButton.tsx
  src/app/board/qna/page.tsx
  src/app/cart/page.tsx
  src/app/category/CategoryPage.tsx
  src/app/order/page.tsx
  src/app/story/[slug]/story-content.tsx
  src/components/common/Breadcrumb.tsx
Labels: enhancement, design

#213 🎨 feat: 관리자 주문목록 추가
  src/app/mypage/admin/orders/AdminOrderCard.tsx
  src/app/mypage/admin/orders/AdminOrdersMobile.tsx
  src/app/mypage/admin/orders/AdminOrdersTable.tsx
  src/app/mypage/admin/orders/AdminOrdersWrapper.tsx
  src/app/mypage/admin/orders/[id]/AdminOrderDetailWrapper.tsx
  src/app/mypage/admin/orders/[id]/BuyerInfo.tsx
  src/app/mypage/admin/orders/[id]/OrderHistory.tsx
  src/app/mypage/admin/orders/[id]/OrderProducts.tsx
  src/app/mypage/admin/orders/[id]/OrderSummary.tsx
  src/app/mypage/admin/orders/[id]/PaymentInfo.tsx
  src/app/mypage/admin/orders/[id]/page.tsx
  src/app/mypage/admin/orders/page.tsx
  src/data/actions/patchOrderState.ts
  src/types/AdminOrder.ts
  src/utils/getAdminOrders.ts
Labels: feature

#217 🎨 feat: 문의게시판 관리자 답변 달기 기능 추가(desktop, mobile)
  src/app/board/qna/[id]/DesktopQNADetail.tsx
  src/app/board/qna/[id]/MobileQNADetail.tsx
Labels: feature, enhancement
