Repository FRONTENDBOOTCAMP-13th/Final-10-console.10g, pull requests merged in 2025-08, with the labels that each got.

#219 🎨 feat: 마이페이지 관리자 UI 구현 및 기타 버그들 해결
  api/dbinit/team/data.js
  package-lock.json
  package.json
  src/app/category/CategoryPage.tsx
  src/app/mypage/AdminGraph.tsx
  src/app/mypage/AdminList.tsx
  src/app/mypage/MypageInfo.tsx
  src/app/mypage/MypageNav.tsx
  src/app/mypage/MypageSection.tsx
  src/app/mypage/ResidentCard.tsx
  src/app/mypage/SendMessage.tsx
  src/app/mypage/page.tsx
  src/app/products/[id]/ProductDetailPage.tsx
  src/app/products/[id]/TabSection.tsx
  src/app/search/page.tsx
  src/components/common/DesktopHeader.tsx
  src/components/common/NotificationIcon.tsx
  src/components/common/TokenExpiration.tsx
  src/data/actions/addNotification.ts
  src/data/actions/authorization.ts
  src/data/actions/patchNotification.ts
  src/stores/loginStore.ts
  src/types/api.ts
  src/types/notification.ts
  src/utils/getAdminStatisticsOrders.ts
Labels: bug, feature, enhancement, design, api

#224 🐛 fix: 잘못 머지된 사항 해결
  src/app/category/CategoryPage.tsx
  src/stores/loginStore.ts
Labels: bug

#229 🐛 fix: 마이페이지 이미지가 수정이 안되는 버그, 알림 이미지가 안보이는 버그 해결
  src/app/mypage/MypageInfo.tsx
  src/app/mypage/ResidentCard.tsx
  src/app/mypage/edit-admin/page.tsx
  src/components/common/NotificationIcon.tsx
  src/data/actions/authorization.ts
  src/stores/loginStore.ts
  src/types/User.ts
Labels: bug

#225 🎨 feat: 이미지 업로드 경로 관련 수정 작업
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/community/ImageModal.tsx
  src/app/board/qna/QnaBoardClientWrapper.tsx
  src/app/board/qna/[id]/DesktopQNADetail.tsx
  src/app/board/qna/[id]/MobileQNADetail.tsx
  src/app/board/qna/new/NewQnaForm.tsx
  src/app/board/qna/new/OrderModal.tsx
  src/app/board/qna/new/ProductSearchModal.tsx
  src/data/actions/post.ts
  src/types/Product.ts
Labels: api

#232 🎨 feat: typeof로 타입 가드
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/community/ImageModal.tsx
Labels: bug, api

#235 🎨feat: 상품 등록 및 수정
  src/app/admin/products/components/CategorySelector.tsx
  src/app/admin/products/create/ProductCreateForm.tsx
  src/app/admin/products/create/page.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/products/[id]/page.tsx
  src/components/common/ReviewModal.tsx
  src/utils/getBookmarkStatus.ts
Labels: feature, refactor, enhancement, design

#237 🎨 feat: 자유게시판 삭제 기능 추가
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/community/ImageModal.tsx
  src/app/board/qna/[id]/DesktopQNADetail.tsx
  src/app/board/qna/[id]/MobileQNADetail.tsx
  src/data/actions/post.ts
Labels: enhancement, api

#239 ♻️ refactor: 회원 가입 시 기본 프로필 설정
  api/dbinit/team/data.json
  api/dbinit/team/uploadFiles/chiikawa.webp
  api/dbinit/team/uploadFiles/conan.webp
  api/dbinit/team/uploadFiles/ganadi.webp
  api/dbinit/team/uploadFiles/hamster.webp
  public/default-profile.webp
  src/app/order/OrderWrapper.tsx
  src/data/actions/user.ts
Labels: refactor

#241 ♻️ refactor: admin/products 접근 권한 제어
  src/app/admin/products/create/ProductCreateForm.tsx
  src/app/admin/products/create/page.tsx
  src/app/admin/products/edit/[id]/ProductEditPage.tsx
  src/app/unauthorized/page.tsx
  src/stores/loginStore.ts
Labels: bug, refactor

#246 🔧 settings: 디비 관련 수정
  api/bruno/team/final/final/DB 초기화.bru
  api/dbinit/team/data.json
  src/components/common/DesktopHeader.tsx
  src/components/common/MobileHeader.tsx
Labels: settings

#244 🐛 fix: 카테고리 슬라이더에 링크 추가
  src/app/(user)/signup/EmailField.tsx
  src/app/admin/products/create/ProductCreateForm.tsx
  src/components/main/CategorySlider.tsx
Labels: bug

#251 💄 style: 관리자 마이페이지 수정
  src/app/mypage/AdminGraph.tsx
  src/app/mypage/AdminList.tsx
  src/app/mypage/MypageInfo.tsx
  src/app/mypage/MypageSection.tsx
  src/components/common/DesktopHeader.tsx
  src/components/common/MobileHeader.tsx
  src/components/common/NotificationIcon.tsx
Labels: design

#253 🐛 fix: total bug 잡기
  public/dotoriQR.png
  src/app/admin/orders/AdminOrdersWrapper.tsx
  src/app/mypage/ResidentCard.tsx
  src/app/order/complete/[id]/OrderCompleteButtons.tsx
  src/app/products/[id]/review/ReviewItem.tsx
  src/components/common/Footer.tsx
Labels: bug

#255 💄 style: 페이지네이션 포인터 추가
  src/components/common/Pagination.tsx
  src/components/main/BestReviewCard.tsx
Labels: enhancement, design

#259 🚀 배포 테스트
  api/dbinit/team/data.js
  src/styles/reset.css
Labels: test

#260 4차 배포 테스트
  api/dbinit/team/data.js
  src/styles/reset.css
Labels: test

#261 🐛 fix: 불필요하게 선언된 변수 삭제
  src/app/messagetest/page.tsx
  src/app/mypage/OrderHistory.tsx
  src/components/common/NotificationIcon.tsx
Labels: bug

#263 🐛 fix: 이미지 배열 오류 수정
  src/app/admin/products/edit/[id]/EditInput.tsx
Labels: bug

#264 🚀 deploy: 4차 배포 테스트
  src/app/admin/products/edit/[id]/EditInput.tsx
Labels: test, deploy

#267 🚀 deploy: 4차 배포 테스트
  src/app/apitest/page.tsx
Labels: bug

#268 🐛 fix: 코드 오류 해결
  src/app/messagetest/page.tsx
  src/app/paytest/page.tsx
  src/app/products/[id]/ProductInfo.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/replytest/page.tsx
Labels: bug

#269 🚀 deploy: 4차 배포 테스트
  src/app/messagetest/page.tsx
  src/app/paytest/page.tsx
  src/app/products/[id]/ProductInfo.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/replytest/page.tsx
Labels: test, deploy

#272 💄 style: 다크모드 전용 스타일 제거, 🐛 fix: 유저 프로필 이미지 경로 수정
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/community/ImageModal.tsx
  src/app/board/qna/edit/[id]/EditQnaForm.tsx
  src/app/board/qna/new/NewQnaForm.tsx
Labels: bug, design

#273 🎨 feat: 주민증 기본 사진 선택 기능
  src/app/(user)/login/page.tsx
  src/app/mypage/MypageInfo.tsx
  src/app/mypage/OrderHistory.tsx
  src/app/mypage/ResidentCard.tsx
  src/stores/loginStore.ts
Labels: bug, feature, design

#280 🔥 remove: 3만원 이상 배송비 무료 로직 삭제
  src/app/admin/products/edit/[id]/EditInput.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/products/[id]/ShoppingGuide.tsx
Labels: bug

#285 💄 style: 버튼 커서 포인터 일괄 추가
  src/app/admin/stats/StatsClient.tsx
  src/app/board/notice/new/NoticePostForm.tsx
  src/app/board/qna/[id]/DesktopQNADetail.tsx
  src/app/board/qna/[id]/MobileQNADetail.tsx
  src/app/board/qna/edit/[id]/EditQnaForm.tsx
  src/app/board/qna/new/NewQnaForm.tsx
Labels: design

#288 💄 style: 문의 폼 타입에 커서 포인터 추가
  src/app/board/qna/new/NewQnaForm.tsx
Labels: design

#290 ♻️ Refactor/logout 282
  src/app/admin/products/components/CategorySelector.tsx
  src/app/admin/products/create/ProductCreateForm.tsx
  src/app/mypage/Logout.tsx
  src/app/mypage/MypageInfo.tsx
  src/app/mypage/logout/page.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/utils/getBookmarkStatus.ts
Labels: bug, enhancement

#291 🐛 fix: 403 응답 에러 처리
  src/app/admin/orders/AdminOrderCard.tsx
  src/app/admin/orders/AdminOrdersTable.tsx
  src/app/admin/orders/AdminOrdersWrapper.tsx
  src/app/cart/CartWrapper.tsx
Labels: bug

#296 🎨feat: 모달 추가, 토큰 만료 시 로그아웃
  src/app/client-layout.tsx
  src/app/layout.tsx
  src/components/common/WelcomeModal.tsx
Labels: feature

#297 📝 docs: README 파일 작성
  README.md
  public/readme/admin-add.png
  public/readme/admin-mypage.png
  public/readme/admin-product.png
  public/readme/user-mypage.png
  public/readme/user-pay.png
  public/readme/user-paylog.png
  public/readme/user-product.png
  public/readmelogo.png
Labels: docs

#298 🎨 feat: 토큰 만료 기간 설정
  src/data/actions/addReview.ts
  src/data/actions/login.ts
Labels: feature, enhancement

#301 ♻️ refactor/toast 299
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/SignupForm.tsx
  src/app/admin/orders/AdminOrdersWrapper.tsx
  src/app/admin/products/create/ProductCreateForm.tsx
  src/app/board/community/CommunityPostCard.tsx
  src/app/board/qna/[id]/DesktopQNADetail.tsx
  src/app/board/qna/[id]/MobileQNADetail.tsx
  src/app/cart/CartWrapper.tsx
  src/app/mypage/MypageNav.tsx
  src/app/mypage/MypageSection.tsx
  src/app/mypage/ResidentCard.tsx
  src/app/mypage/SendMessage.tsx
  src/app/mypage/address/add/AddAddress.tsx
  src/app/mypage/address/components/AddressField.tsx
  src/app/mypage/address/edit/[id]/EditAddress.tsx
  src/app/mypage/edit-info/AddressField.tsx
  src/app/mypage/edit-info/EditForm.tsx
  src/app/mypage/wishlist/ProductCard.tsx
  src/app/mypage/wishlist/Wishlist.tsx
  src/app/order/OrderClient.tsx
  src/app/order/OrderWrapper.tsx
  src/app/products/[id]/PurchaseSection.tsx
  src/app/products/[id]/review/index.tsx
  src/components/common/MobileHeader.tsx
  src/components/common/NotificationIcon.tsx
  src/components/common/TokenExpiration.tsx
  src/components/main/CategorySlider.tsx
  src/components/main/PopularSection.tsx
  src/components/main/ReviewSlider.tsx
  src/data/actions/addBookmark.ts
  src/hooks/useToggleBookmark.ts
Labels: refactor, enhancement

#303 🐛 fix: 쪽지 이미지가 안나오는 버그 해결
  README.md
  src/components/common/NotificationIcon.tsx
Labels: bug

#306 🐛 fix: 유저, 글 정보 force-cache를 no-store로 변경
  api/bruno/team/final/final/DB 초기화2.bru
  api/dbinit/team/data.json
  api/dbinit/team/uploadFiles/PC0102_03.webp
  api/dbinit/team/uploadFiles/PC0102_04.webp
  api/dbinit/team/uploadFiles/PC0102_05.webp
  src/app/category/CategoryPage.tsx
  src/utils/getPosts.ts
  src/utils/getUsers.ts
Labels: bug

#307 🚀 deploy: 배포
  api/bruno/team/final/final/DB 초기화2.bru
  api/dbinit/team/data.json
  api/dbinit/team/uploadFiles/PC0102_03.webp
  api/dbinit/team/uploadFiles/PC0102_04.webp
  api/dbinit/team/uploadFiles/PC0102_05.webp
  src/app/category/CategoryPage.tsx
  src/utils/getPosts.ts
  src/utils/getUsers.ts
Labels: deploy

#311 🐛 fix: 불필요한 props 제거
  src/app/board/community/CommunityBoardClientWrapper.tsx
  src/app/board/community/page.tsx
Labels: bug

#317 📝 docs: README 파일 수정
  README.md
  src/app/mypage/AdminGraph.tsx
Labels: docs, design

#318 🚀 deploy: 배포
  README.md
  src/app/mypage/AdminGraph.tsx
Labels: deploy

#320 🐛 fix: 카테고리 페이지 해당 상품이 없다는 메시지가 나오는 오류 해결
  src/app/category/CategoryPage.tsx
Labels: bug

#321 🚀 deploy: 배포
  src/app/category/CategoryPage.tsx
Labels: deploy

#322 🐛 fix: 로그아웃 유저한테 상품이 안뜨는 버그 해결
  src/app/category/CategoryPage.tsx
Labels: bug

#323 🚀 deploy: 배포
  src/app/category/CategoryPage.tsx
Labels: deploy
